name: automerge

on:
  pull_request:
    branches:
      - master

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - name: PR Labeler
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  automerge:
    needs: pr-labeler
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.7.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "weekly"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "automatic"
          MERGE_FORKS: "true"
          MERGE_DELETE_BRANCH: "true"
          UPDATE_LABELS: "weekly"
          UPDATE_METHOD: "merge"
